// Block types: h = section heading, p = paragraph, b = bold paragraph,
// ul = bullet list, table = { head, rows }.
export const privacy = {
  en: {
    title: 'Privacy Policy',
    dates: ['Effective date: 1 October 2026', 'Last updated: 1 October 2026'],
    blocks: [
      { p: 'PlayFeat is a hand-gesture cooking game for iPhone, iPad, and Mac. You play it by moving your hands in front of the camera: grabbing ingredients, dropping them into the bowl, and serving the finished dish.' },
      { p: 'This policy explains exactly what the app does with your camera, and what it does not do.' },
      { p: 'PlayFeat contains a single game — the cooking game — and no other games or modules. This policy covers the entire app.' },
      { h: 'The short version' },
      { b: 'PlayFeat does not collect, store, or share any personal data.' },
      { p: 'The app needs your camera to work, but the camera images never leave your device, are never recorded, and are never sent anywhere. The app has no servers, no accounts, and no internet features of any kind.' },
      { h: '1. Information we collect' },
      { b: 'None.' },
      { p: 'We do not collect, request, or receive:' },
      { ul: [
        'Names, email addresses, phone numbers, or usernames',
        'Accounts, logins, or profiles',
        'Photos, videos, or audio recordings',
        'Location data',
        'Contacts, calendars, or files',
        'Device identifiers, advertising IDs, or analytics data',
        'Crash reports or usage statistics',
        'Payment or financial information',
      ] },
      { p: 'There is no sign-up, no login, and no way to create a profile in PlayFeat.' },
      { h: '2. How the camera is used' },
      { p: 'PlayFeat requires access to the front-facing camera. This is the only permission the app asks for, and the game cannot function without it.' },
      { p: 'Here is precisely what happens:' },
      { ul: [
        'The live camera image is shown on screen so you can see yourself behind the game, which creates the augmented-reality effect.',
        "Each frame is analysed on your device by Apple's Vision framework to estimate the position of your hand joints (wrist, knuckles, fingertips).",
        'The game uses those positions to move the cursor, detect an open hand or a closed fist, and recognise swipe and clap gestures.',
        'The frame is then discarded immediately.',
      ] },
      { p: 'What this means in practice:' },
      { ul: [
        "Camera frames exist only momentarily in your device's memory while being analysed.",
        'Nothing is written to storage. The app never saves photos, video, or screenshots.',
        'Nothing is transmitted. The app contains no networking code whatsoever.',
        'The app does not perform face recognition, face identification, age estimation, or emotion detection. It analyses hand geometry only.',
        'Hand position data is used in the moment to run the game and is never stored or logged.',
      ] },
      { p: "All camera processing happens locally using Apple's on-device frameworks (AVFoundation and Vision). No cloud or remote processing service is involved." },
      { h: '3. Internet access' },
      { b: 'PlayFeat works entirely offline.' },
      { p: 'The app contains no network requests, no remote servers, no cloud storage, and no third-party backend. You can play it in Airplane Mode with no loss of functionality.' },
      { h: '4. Third parties' },
      { b: 'PlayFeat includes no third-party SDKs, libraries, analytics tools, advertising networks, or trackers.' },
      { p: "The app is built only on Apple's own frameworks (SwiftUI, SpriteKit, AVFoundation, and Vision), all of which run on your device. No data is shared with us or with anyone else, because no data is ever produced." },
      { h: '5. Advertising and tracking' },
      { b: 'PlayFeat shows no advertisements and performs no tracking.' },
      { p: 'The app does not use the Advertising Identifier (IDFA), does not present App Tracking Transparency prompts, and does not build user profiles or track you across apps or websites.' },
      { h: '6. Data storage and retention' },
      { b: 'PlayFeat stores nothing — not on your device, and not anywhere else.' },
      { p: 'Your score and the round timer exist only in memory while the game is running. When you close the app, they are gone. There is no saved game, no high-score history, and no settings file containing personal information.' },
      { p: 'Because no data is collected or retained, there is no data to delete, export, or request.' },
      { h: '7. Permissions and your control' },
      { table: {
        head: ['Permission', 'Required', 'Why'],
        rows: [
          ['Camera', 'Yes', 'Hand-gesture controls and the on-screen camera background'],
          ['Microphone', 'No', 'Not requested'],
          ['Photos', 'No', 'Not requested'],
          ['Location', 'No', 'Not requested'],
          ['Contacts', 'No', 'Not requested'],
        ],
      } },
      { p: 'You are asked for camera permission the first time you open the game. You can revoke it at any time:' },
      { ul: [
        'iPhone / iPad: Settings → Privacy & Security → Camera → PlayFeat',
        'Mac: System Settings → Privacy & Security → Camera → PlayFeat',
      ] },
      { p: 'If you deny or revoke camera access, the app will show a message explaining that the camera is required, and the game will not be playable. No other part of the app is affected, and no penalty or data collection results from declining.' },
      { h: "8. Children's privacy" },
      { b: 'PlayFeat is suitable for children and collects no personal information from users of any age.' },
      { p: 'Because the app collects nothing, stores nothing, and transmits nothing, it does not knowingly or unknowingly gather data from children under 13 (or the equivalent age in your country). There are no in-app purchases, no advertisements, no chat features, and no links out to external websites.' },
      { p: 'Parents and guardians should be aware that the game uses the front camera to display the player on screen during play. This image is shown live on the device only and is never recorded or shared.' },
      { h: '9. Your rights' },
      { p: "Privacy regulations such as the GDPR (Europe), CCPA (California), and Indonesia's Personal Data Protection Law (UU PDP No. 27/2022) grant rights to access, correct, delete, and port your personal data." },
      { p: 'PlayFeat holds no personal data about you, so there is nothing for us to access, correct, delete, or transfer. You retain full control simply by managing the camera permission on your device.' },
      { h: '10. Changes to this policy' },
      { p: 'If the app changes in a way that affects privacy — for example if online leaderboards, analytics, or accounts are ever added — this policy will be updated before that version is released, and the "Last updated" date above will change.' },
      { p: 'As it stands, the app is intentionally offline and self-contained.' },
      { h: '11. Contact' },
      { p: 'If you have questions about this privacy policy or how PlayFeat handles your data, contact:' },
      { p: '[playfeatdevs@gmail.com]' },
    ],
  },
  id: {
    title: 'Kebijakan Privasi',
    dates: ['Tanggal berlaku: 1 Oktober 2026', 'Terakhir diperbarui: 1 Oktober 2026'],
    blocks: [
      { p: 'PlayFeat adalah game memasak berbasis gerakan tangan untuk iPhone, iPad, dan Mac. Kamu bermain dengan menggerakkan tangan di depan kamera: mengambil bahan, memasukkannya ke mangkuk, dan menyajikan hidangan.' },
      { p: 'Kebijakan ini menjelaskan secara persis apa yang dilakukan aplikasi terhadap kamera kamu, dan apa yang tidak dilakukannya.' },
      { p: 'PlayFeat hanya berisi satu game — game memasak — dan tidak ada game atau modul lain. Kebijakan ini mencakup keseluruhan aplikasi.' },
      { h: 'Ringkasan singkat' },
      { b: 'PlayFeat tidak mengumpulkan, menyimpan, atau membagikan data pribadi apa pun.' },
      { p: 'Aplikasi ini membutuhkan kamera untuk berfungsi, tetapi gambar kamera tidak pernah keluar dari perangkat kamu, tidak pernah direkam, dan tidak pernah dikirim ke mana pun. Aplikasi ini tidak memiliki server, tidak memiliki akun, dan tidak memiliki fitur internet apa pun.' },
      { h: '1. Informasi yang kami kumpulkan' },
      { b: 'Tidak ada.' },
      { p: 'Kami tidak mengumpulkan, meminta, atau menerima:' },
      { ul: [
        'Nama, alamat email, nomor telepon, atau nama pengguna',
        'Akun, login, atau profil',
        'Foto, video, atau rekaman suara',
        'Data lokasi',
        'Kontak, kalender, atau berkas',
        'Identifier perangkat, ID iklan, atau data analitik',
        'Laporan kerusakan (crash report) atau statistik penggunaan',
        'Informasi pembayaran atau keuangan',
      ] },
      { p: 'Tidak ada pendaftaran, tidak ada login, dan tidak ada cara untuk membuat profil di PlayFeat.' },
      { h: '2. Bagaimana kamera digunakan' },
      { p: 'PlayFeat memerlukan akses ke kamera depan. Ini adalah satu-satunya izin yang diminta aplikasi, dan game tidak dapat berjalan tanpanya.' },
      { p: 'Berikut yang terjadi secara persis:' },
      { ul: [
        'Gambar kamera langsung ditampilkan di layar agar kamu bisa melihat dirimu sendiri di belakang game, sehingga tercipta efek augmented reality.',
        'Setiap frame dianalisis di perangkatmu menggunakan framework Vision milik Apple untuk memperkirakan posisi sendi tangan (pergelangan, buku jari, ujung jari).',
        'Game menggunakan posisi tersebut untuk menggerakkan kursor, mendeteksi tangan terbuka atau mengepal, serta mengenali gerakan swipe dan tepuk tangan.',
        'Frame tersebut langsung dibuang setelahnya.',
      ] },
      { p: 'Artinya dalam praktik:' },
      { ul: [
        'Frame kamera hanya ada sesaat di memori perangkat saat sedang dianalisis.',
        'Tidak ada yang ditulis ke penyimpanan. Aplikasi tidak pernah menyimpan foto, video, atau tangkapan layar.',
        'Tidak ada yang dikirim. Aplikasi sama sekali tidak memiliki kode jaringan.',
        'Aplikasi tidak melakukan pengenalan wajah, identifikasi wajah, perkiraan usia, atau deteksi emosi. Yang dianalisis hanya geometri tangan.',
        'Data posisi tangan dipakai saat itu juga untuk menjalankan game dan tidak pernah disimpan atau dicatat.',
      ] },
      { p: 'Seluruh pemrosesan kamera terjadi secara lokal menggunakan framework Apple (AVFoundation dan Vision). Tidak ada layanan cloud atau pemrosesan jarak jauh yang terlibat.' },
      { h: '3. Akses internet' },
      { b: 'PlayFeat berfungsi sepenuhnya secara offline.' },
      { p: 'Aplikasi ini tidak memiliki permintaan jaringan, server jarak jauh, penyimpanan cloud, maupun backend pihak ketiga. Kamu bisa memainkannya dalam Mode Pesawat tanpa kehilangan fungsi apa pun.' },
      { h: '4. Pihak ketiga' },
      { b: 'PlayFeat tidak menyertakan SDK, pustaka, alat analitik, jaringan iklan, atau pelacak pihak ketiga.' },
      { p: 'Aplikasi ini dibangun hanya di atas framework milik Apple (SwiftUI, SpriteKit, AVFoundation, dan Vision), yang semuanya berjalan di perangkatmu. Tidak ada data yang dibagikan kepada kami maupun pihak lain, karena memang tidak ada data yang dihasilkan.' },
      { h: '5. Iklan dan pelacakan' },
      { b: 'PlayFeat tidak menampilkan iklan dan tidak melakukan pelacakan.' },
      { p: 'Aplikasi tidak menggunakan Advertising Identifier (IDFA), tidak menampilkan permintaan App Tracking Transparency, dan tidak membangun profil pengguna atau melacakmu antar aplikasi maupun situs web.' },
      { h: '6. Penyimpanan dan retensi data' },
      { b: 'PlayFeat tidak menyimpan apa pun — baik di perangkatmu maupun di tempat lain.' },
      { p: 'Skor dan timer hanya ada di memori selama game berjalan. Saat kamu menutup aplikasi, semuanya hilang. Tidak ada simpanan permainan, tidak ada riwayat skor tertinggi, dan tidak ada berkas pengaturan yang berisi informasi pribadi.' },
      { p: 'Karena tidak ada data yang dikumpulkan atau disimpan, tidak ada data yang perlu dihapus, diekspor, atau diminta.' },
      { h: '7. Izin dan kendali kamu' },
      { table: {
        head: ['Izin', 'Diperlukan', 'Alasan'],
        rows: [
          ['Kamera', 'Ya', 'Kontrol gerakan tangan dan latar kamera di layar'],
          ['Mikrofon', 'Tidak', 'Tidak diminta'],
          ['Foto', 'Tidak', 'Tidak diminta'],
          ['Lokasi', 'Tidak', 'Tidak diminta'],
          ['Kontak', 'Tidak', 'Tidak diminta'],
        ],
      } },
      { p: 'Kamu akan dimintai izin kamera saat pertama kali membuka game. Kamu dapat mencabutnya kapan saja:' },
      { ul: [
        'iPhone / iPad: Pengaturan → Privasi & Keamanan → Kamera → PlayFeat',
        'Mac: Pengaturan Sistem → Privasi & Keamanan → Kamera → PlayFeat',
      ] },
      { p: 'Jika kamu menolak atau mencabut akses kamera, aplikasi akan menampilkan pesan bahwa kamera diperlukan, dan game tidak dapat dimainkan. Tidak ada bagian lain dari aplikasi yang terpengaruh, dan tidak ada konsekuensi atau pengumpulan data akibat penolakan tersebut.' },
      { h: '8. Privasi anak' },
      { b: 'PlayFeat aman untuk anak-anak dan tidak mengumpulkan informasi pribadi dari pengguna usia berapa pun.' },
      { p: 'Karena aplikasi tidak mengumpulkan, menyimpan, maupun mengirim apa pun, aplikasi ini tidak mengumpulkan data dari anak di bawah 13 tahun (atau usia setara di negaramu), baik secara sengaja maupun tidak. Tidak ada pembelian dalam aplikasi, tidak ada iklan, tidak ada fitur obrolan, dan tidak ada tautan ke situs web eksternal.' },
      { p: 'Orang tua dan wali perlu mengetahui bahwa game ini menggunakan kamera depan untuk menampilkan pemain di layar selama bermain. Gambar ini hanya ditampilkan secara langsung di perangkat dan tidak pernah direkam atau dibagikan.' },
      { h: '9. Hak kamu' },
      { p: 'Peraturan privasi seperti GDPR (Eropa), CCPA (California), dan Undang-Undang Pelindungan Data Pribadi Indonesia (UU PDP No. 27/2022) memberikan hak untuk mengakses, mengoreksi, menghapus, dan memindahkan data pribadimu.' },
      { p: 'PlayFeat tidak menyimpan data pribadi apa pun tentangmu, sehingga tidak ada yang bisa kami akses, koreksi, hapus, atau pindahkan. Kamu tetap memegang kendali penuh cukup dengan mengatur izin kamera di perangkatmu.' },
      { h: '10. Perubahan kebijakan ini' },
      { p: 'Jika aplikasi berubah dengan cara yang memengaruhi privasi — misalnya jika papan peringkat daring, analitik, atau akun ditambahkan — kebijakan ini akan diperbarui sebelum versi tersebut dirilis, dan tanggal "Terakhir diperbarui" di atas akan berubah.' },
      { p: 'Untuk saat ini, aplikasi sengaja dibuat offline dan mandiri.' },
      { h: '11. Kontak' },
      { p: 'Jika kamu memiliki pertanyaan tentang kebijakan privasi ini atau bagaimana PlayFeat menangani datamu, hubungi:' },
      { p: '[playfeatdevs@gmail.com]' },
    ],
  },
}
